name: 'CI/CD tuning contest v0.0.1'

on:
  workflow_dispatch:

jobs:
  post-job: # レギュレーション上必須
    # TODO: 計測結果をスコアボードに送信する処理を入れる
    needs: [fmt-lint-build-test-deploy]
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: Kesin11/actions-timeline@1c2ab3f28225878ae4dd1f76d31279f16ea29e29 # v2.1.1
  fmt-lint-build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Format, Lint, Build, Test, and Deploy
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - run: go fmt ./...
      - run: go vet ./...
      - run: docker build -t myapp .
